certificates:
  ca:
    name: ['ca']
  admin:
    name: ['admin','mkoyan']
  worker:
    name: ['worker-1','worker-2']
  kube-controller-manager:
    name: ['kube-controller-manager-1','kube-controller-manager-2']

global:
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8vuYTJs0b/fRAy97mXI9pOnL/gPknFpt4r/5tK8n7MnLXnfUY5zNIXbyrNxFhPuvB961no9yjeuis1c1UwKsdh8tmYhZn4eMWD7YXMwMlpU1Sk5+CJo7xBqQu62CcJbcvuXzUTco1ytnEqyhDZGmAQT3t4QaKKVkBFx17jpiz4subNR4xiIl+NGKWRmnrBru+AW4BhgsWfqZ3PuFnvSb7NNtpzBv8RnHDE58gXpFdbH+n7QhVyPY0ObBeeunOPTdxQ0rdK4RIsqQEujze6Fxex44d46rA8YsCmfW2XG+loVrvNv6OCPNt5l7fArgr9DYWZtkme5uCflTjrDZPlPcF mkoyan@devops"
    password_hash: "$6$rounds=4096$J5D/WMPiRMY$Y8SsVHtgfz0nBXY8SrYOqW3qZEVUYF2ZsN5dUYQS0zzx7B/fwHCRdBTqo2Zbn3w7o4vxNs57bMlDQk8JN3A1e/"
etcd:
    coreos-1: 
        hostname: "coreos-1"
        ip: "10.100.130.111"

    coreos-2:
        hostname: "coreos-2"
        ip: "10.100.130.112"
        
    coreos-3:
        hostname: "coreos-3"
        ip: "10.100.130.113"
      
    coreos-4:
        hostname: "coreos-4"
        ip: "10.100.130.114"

api-servers:
    api-server-1:
      hostname: "api-server-1:"
      ip: "10.100.130.115"

    api-server-2:
      hostname: "api-server-1:"
      ip: "10.100.130.116"

worker:
    worker-1:
      hostname: 'worker-1'
      ip: '10.100.130.200'
    worker-2:
      hostname: 'worker-2'
      ip: '10.100.130.201'