#cloud-config

update:
  group:  "alpha"
locksmith:
  reboot_strategy: "etcd-lock"
  etcd_endpoints:  "https://10.100.130.111:2379,https://10.100.130.112:2379,https://10.100.130.113:2379"
  etcd_cafile:      "/var/lib/etcd/ssl/ca.pem"
  etcd_certfile:    "/var/lib/etcd/ssl/etcd-nodes.pem"
  etcd_keyfile:     "/var/lib/etcd/ssl/etcd-nodes-key.pem"

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8vuYTJs0b/fRAy97mXI9pOnL/gPknFpt4r/5tK8n7MnLXnfUY5zNIXbyrNxFhPuvB961no9yjeuis1c1UwKsdh8tmYhZn4eMWD7YXMwMlpU1Sk5+CJo7xBqQu62CcJbcvuXzUTco1ytnEqyhDZGmAQT3t4QaKKVkBFx17jpiz4subNR4xiIl+NGKWRmnrBru+AW4BhgsWfqZ3PuFnvSb7NNtpzBv8RnHDE58gXpFdbH+n7QhVyPY0ObBeeunOPTdxQ0rdK4RIsqQEujze6Fxex44d46rA8YsCmfW2XG+loVrvNv6OCPNt5l7fArgr9DYWZtkme5uCflTjrDZPlPcF mkoyan@devops
networkd:
  units:
    - name: 00-ens192.network
      contents: |
        [Match]
        Name=ens192

        [Network]
        DNS=10.100.130.1
        Address=10.100.130.113/24
        Gateway=10.100.130.1
storage:
  files:
    - filesystem: "root"
      path:       "/etc/metadata/coreos"
      mode:       0644
      contents:
        inline: |
          COREOS_PRIVATE_IPV4=10.100.130.113
          COREOS__HOSTNAME=coreos-3
    - filesystem: "root"
      path:       "/etc/environment"
      mode:       0644
      contents:
        inline: |
          export ETCDCTL_CACERT=/var/lib/etcd/ssl/ca.pem
          export ETCDCTL_CERT=/var/lib/etcd/ssl/etcd-nodes.pem
          export ETCDCTL_KEY=/var/lib/etcd/ssl/etcd-nodes-key.pem
          export ETCDCTL_API=3 
          export ETCDCTL_ENDPOINTS=https://10.100.130.111:2379,https://10.100.130.112:2379,https://10.100.130.113:2379
    - filesystem: "root"
      path:       "/etc/hostname"
      mode:       0644
      contents:
        inline: coreos-3.mkoyan.local       
    - filesystem: "root"
      path:       "/etc/hosts"
      mode:       0644
      contents:
        inline: |
          127.0.0.1	localhost
          ::1		localhost 
          10.100.130.111 coreos-1 coreos-1.mkoyan.local
          10.100.130.112 coreos-2 coreos-2.mkoyan.local
          10.100.130.113 coreos-3 coreos-3.mkoyan.local
    - filesystem: root
      path: "/etc/motd"
      mode: 0644
      contents:
        inline: | 
          Hey Mkoyan!
    - path: /etc/systemd/timesyncd.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          [Time]
          NTP=10.100.130.1
    - path: /var/lib/etcd/ssl/ca.pem
      filesystem: root
      mode: 0644
      contents:
        inline: |
          -----BEGIN CERTIFICATE-----
          MIIDfzCCAmegAwIBAgIJAIjBdb8zuCZvMA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNV
          BAYTAkFNMQ8wDQYDVQQIDAZZZXJ2YW4xDzANBgNVBAcMBlllcnZhbjEVMBMGA1UE
          CgwMbWtveWFuLmxvY2FsMRUwEwYDVQQDDAxta295YW4ubG9jYWwwHhcNMTkwMzE4
          MTEwMTQzWhcNMjkwMzE1MTEwMTQzWjBdMQswCQYDVQQGEwJBTTEPMA0GA1UECAwG
          WWVydmFuMQ8wDQYDVQQHDAZZZXJ2YW4xFTATBgNVBAoMDG1rb3lhbi5sb2NhbDEV
          MBMGA1UEAwwMbWtveWFuLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAw7WmWvK09wnisgJk7iXpAQxMmaN/TmQzx20+7VUlHh3eMtuf0dAbWDav
          N8gtECURNah75Fb4OAesyc2h+4TrY/PDjNialIR3nTVSFMbyB8TeBGCvnqyDYk5e
          P7Qr1l58LRN0TxnfeBhP3QFHcAZBj35Y646jvSCeTkcc2VYd+KKJsURQenWxM77h
          fAnqoMFgfJwzBCB0mSDNSooEqXLWNPZT3Fa37/xQM/V2mRfqHu5M8J6+oRrt/iGv
          2Xzzg3st/rVawx99Lji25hiKnJeP59s2E9vxdKuL3ra/ZRaIdSCUBlLM1mEJqtJ6
          o1b3SijwfBtDSVRfRLPZWnZmRYf66wIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYw
          DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUcPmQa4KCQ46e7YV4F3ne1UaHPeAw
          DQYJKoZIhvcNAQELBQADggEBAB0yGwbH38Yf1kW2FHWc/oEQWTOfbl3yWUJ1LxO8
          RjPnt+DZuLTBlsKB4P1/aDXNzwDNxMkDm7yKygp4bgd+rVjnP+iVw24rl5N2gyPj
          n/cuRbhIEnd/a/76J79tWL+ar/W9zqBCBVBHDiE+Yg6ZmVu1HNHPIcbUjDCwbFBY
          2nzZw52dheeLiyjF+df5g0bWOgLAj/jtwmhrcA89pJPbilEJoJ2AlQOXga6LPYVH
          Q6RZdIZQGqsOJRli8tfTAMCeZr/kx/ccJZ3pMUxQlK9HdhSrzo63Ri1HrK0uopUI
          s2deH14CLHupM/aL3BR08oGjXVcDJVoY4rGoFtc86qn1MaY=
          -----END CERTIFICATE-----
    - path: /var/lib/etcd/ssl/etcd-nodes.pem
      filesystem: root
      mode: 0644
      contents:
        inline: |
          -----BEGIN CERTIFICATE-----
          MIIFMDCCBBigAwIBAgIJALWF5+t9HxjjMA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNV
          BAYTAkFNMQ8wDQYDVQQIDAZZZXJ2YW4xDzANBgNVBAcMBlllcnZhbjEVMBMGA1UE
          CgwMbWtveWFuLmxvY2FsMRUwEwYDVQQDDAxta295YW4ubG9jYWwwHhcNMTkwMzE4
          MTEwMTQzWhcNMjkwMzE1MTEwMTQzWjBbMQswCQYDVQQGEwJBTTEPMA0GA1UECAwG
          WWVydmFuMQ8wDQYDVQQHDAZZZXJ2YW4xFTATBgNVBAoMDG1rb3lhbi5sb2NhbDET
          MBEGA1UEAwwKZXRjZC1ub2RlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
          ggEBAN9z0u3cYJRsF0uQ71QtD3Op1Ct4QGRTEpM172ZuJKzZGB3SnKmQfqtQFHGZ
          RcLS2heper85YPt97qOvHCrak5ZQnt91Ad3DVkjZgSa/ri6CxEGMWeSaUgKM5QCH
          xWKjZKX/PX2kVYyD0j9o/kOAsTRxy9BxxEf5wpDfr+ZEMZDwC7E3RZ2AdwBo1BmB
          aZYPSUK80ClduPppEuV7kTndD8JPO3FpfT8HEeOEY4dEV8LcSWRlww3HVup7iAi7
          4AZDK3ocMsnGmm43r2bJnuAD/2/o0r1p4ZCXBdHwKi0gh6YIknNJBWNUZvf6Bcwh
          GuDNLL3+xIw6bMCtU1E7W8w/+UsCAwEAAaOCAfMwggHvMA4GA1UdDwEB/wQEAwIF
          4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAd
          BgNVHQ4EFgQUXApMLaiXdkbmaftRE9X5D9Ow1TUwggGPBgNVHREEggGGMIIBgoIM
          bWtveWFuLmxvY2FsghVjb3Jlb3MtMS5ta295YW4ubG9jYWyCFWNvcmVvcy0yLm1r
          b3lhbi5sb2NhbIIVY29yZW9zLTMubWtveWFuLmxvY2Fsgglsb2NhbGhvc3SCCGNv
          cmVvcy0xgghjb3Jlb3MtMoIIY29yZW9zLTOCDmNvcmVvcy0xLmxvY2Fsgg5jb3Jl
          b3MtMi5sb2NhbIIOY29yZW9zLTMubG9jYWyCCmt1YmVybmV0ZXOCEmt1YmVybmV0
          ZXMuZGVmYXVsdIIWa3ViZXJuZXRlcy5kZWZhdWx0LnN2Y4Ika3ViZXJuZXRlcy5k
          ZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fsgg5rdWJlLWFwaXNlcnZlcoIKa3ViZS1h
          ZG1pbocEfwAAAYcECmSCb4cECmSCcIcECmSCcYcECmSCc4cECmSCdIcECmSCdYcE
          CmSCdocECgMAAYcECmSCAYcECmSCAocEAAAAAIESYWRtaW5AbWtveWFuLmxvY2Fs
          MA0GCSqGSIb3DQEBCwUAA4IBAQCbbT8TsSN6gHhZVKdO9IsgvJVCycEP2XhY9RwC
          vNIEV0ywAJ1nk4EmlHkqmSuWUuNfy3Yrgs/6aGAdpVzHIlPfo7OYgNgqCSmqB6l1
          WH+wD9Tbsx3c0he/Gi9+e+8t0HqPUmxR06O0RbPjokWuMyPWw1ARUrl3hVMwcPkb
          /0jkIzjbv+Zp9WaqcvwvD5JxiD4LH45XjgPP6buvB8Iq0bwG8PTPbeonhhL7G9Im
          6ywEodEcayAJ/k9qWozPDCuOe5B3KgSdL9YgW8Y29nq4gfIFhewVGELX9tj1No+q
          w1iH/3SwpQk1UJTxEi+0eZth2Hcs4jtjQZ0oM6qwbb+tB+Ql
          -----END CERTIFICATE-----
    - path: /var/lib/etcd/ssl/etcd-nodes-key.pem
      filesystem: root
      mode: 0644
      contents:
        inline: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEA33PS7dxglGwXS5DvVC0Pc6nUK3hAZFMSkzXvZm4krNkYHdKc
          qZB+q1AUcZlFwtLaF6l6vzlg+33uo68cKtqTllCe33UB3cNWSNmBJr+uLoLEQYxZ
          5JpSAozlAIfFYqNkpf89faRVjIPSP2j+Q4CxNHHL0HHER/nCkN+v5kQxkPALsTdF
          nYB3AGjUGYFplg9JQrzQKV24+mkS5XuROd0Pwk87cWl9PwcR44Rjh0RXwtxJZGXD
          DcdW6nuICLvgBkMrehwyycaabjevZsme4AP/b+jSvWnhkJcF0fAqLSCHpgiSc0kF
          Y1Rm9/oFzCEa4M0svf7EjDpswK1TUTtbzD/5SwIDAQABAoIBAE7wK+O7pqLITLJ1
          URb7lCnYJQv2P0kxz64Rr7EP2AT37H0cmhuM4DLE53P6IZrhwgn55VMIgipWIqfQ
          hLLe5KSFdpqaSz58c07pB6cYr//eUlaVrmwD2FTuUTgOvrxJ3JSHxsFL/KzXJL8h
          6DEQlYlhag8JIb4LjaCAZTODg78fZPYDrvuK+0atRwxN1us1wAkP+2XgApFT0XUg
          KMQEoBJUYhCfIOjkWLOo4XS1Bzb/sK7dSvawKWfuAs35DO5V3ZY1eb24AA1MWHsl
          BeqIn/oleagBeZo/fEZF3tZgeASKn9uJRhwkgVwn7Ifm8BXCM/+ZImgsxaAMY3Lj
          3N3sGoECgYEA9axvsOfV1OxragA8r1fYM3CHyUNWLZFJEIU+95/6rJsdTlj8YZyy
          oYlUs5TtQDTs3lxPqy4Di7DQPw/7m2FNimyNq8IMeFPATaHr4fEAQ4PnqMzHA0mF
          YIl13crcOoGcsyGgNkVECL+EYRGJTcFFnQfTR8QbmuXEyQTGBlzxBHUCgYEA6NhH
          FVZf5f8E3sIrvxi+1W+p65ak6HRgjbAviApBhhsdiDJrf65NWDP0XP+22YAPLag4
          ITTqia0dRz81zEI1XVY8cCwnI6MWMK4SRVeW0DyeZtPaOcqYYoV9mnIyc00VT5f4
          wfczmjA3+uPGxefzuibl78OHlFKoz6iNOGaKTr8CgYB9EqXmRZFKjnZ9B9PdXPaX
          8aFfqKV2G3I8M+oDvXGscGfyHEGZHGKg9L6nkplax9cTuaFhv9JUStcqU+O/jkEg
          yPUzTV514AWWQGpLpBuDQ+Mrv91N4h9CL5lPKlkGfDgfxm2/U3I4lfA6Tug9Krlb
          IcHB1qhLKtENmh2K3cRihQKBgFz2BCMzsePMVfBtizOnOIFULH3fTgV0eRv4bHGe
          zpww9TBsGNkICN8fFv+OJD1f0C+FSquPSdgfomHQjbT39gBGrqiGKDYlJXXX+Xlv
          x8lpekBJcoXCKeajrwrbbuLzsn9tiCZAgHydpavoBnL68Sav4vs/kECaY8VMYN1U
          qwFXAoGBAIzIx1JyKyXEfQrNQrt8hU7rk8XFBwxG0w88MwUFuYJyFiRvqYX+9cV3
          FyWdj5bQs6OaiziiIN28U2cGUqQ5GOuaybpFBk5/OgFxinDU2fcEaBWGxSHZkF0G
          cwRhdYxrAXJ5CPdcX2TsxqhlQrELxYvNV1d+eT/mULr2wbHhYIr6
          -----END RSA PRIVATE KEY-----

etcd:
  # Human-readable name for this member.
  name:                        "coreos-3"
  data_dir:                    "/var/lib/etcd"
  # list of peer memebr with name=schema
  initial_cluster:              "coreos-1=https://10.100.130.111:2380,coreos-2=https://10.100.130.112:2380,coreos-3=https://10.100.130.113:2380"
  # URLs to advertise to the rest of the cluster
  initial_advertise_peer_urls:  "https://10.100.130.113:2380"
  # This flag tells the etcd to accept incoming requests from its peers
  listen_peer_urls:             "https://10.100.130.113:2380"
  # accept client incoming connection
  listen_client_urls:           "https://10.100.130.113:2379"
  advertise_client_urls:        "https://10.100.130.113:2379"
  # unique cluster id 
  initial_cluster_token:        "etcd-cluster-1"
  # if existing join to cluster with toke of $initial_cluster_token
  initial_cluster_state:        "new"
  
  # enable client cert auth
  client_cert_auth:             true
  cert_file:                    "/var/lib/etcd/ssl/etcd-nodes.pem"            
  key_file:                     "/var/lib/etcd/ssl/etcd-nodes-key.pem"
  trusted_ca_file:              "/var/lib/etcd/ssl/ca.pem"
  
  # enable peer cert auth
  peer_client_cert_auth:        true      
  peer_cert_file:               "/var/lib/etcd/ssl/etcd-nodes.pem"
  peer_key_file:                "/var/lib/etcd/ssl/etcd-nodes-key.pem"
  peer_trusted_ca_file:         "/var/lib/etcd/ssl/ca.pem"